# Generated by Django 5.2.4 on 2025-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entite_budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_initial', models.FloatField()),
                ('cout_reel', models.FloatField(default=0.0)),
                ('reste_a_payer', models.FloatField(default=0.0)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='entite_budget.entitebudgetee')),
            ],
        ),
    ]
