# Generated by Django 5.2.4 on 2025-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ressource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceMaterielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristique', models.TextField(blank=True)),
                ('ressource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materielle', to='ressource.ressource')),
            ],
        ),
    ]
