# Generated by Django 5.2.4 on 2025-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='fermé', max_length=50)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chantiers', to='projet.projet')),
            ],
        ),
    ]
