# Generated by Django 5.2.4 on 2025-09-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0001_initial'),
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('quantite', models.FloatField(default=0.0)),
                ('unite', models.CharField(blank=True, max_length=50)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='fournisseur.fournisseur')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='tache.tache')),
            ],
        ),
    ]
